### ISSUE TITLE
unable to use hostapd

### ISSUE THREAD

**Issue by vighnesh91** [vanhoefm/krackattacks#32]
[09:07:03] Failed to get MAC address of wlan0. Specify an existing interface in hostapd.conf at the line "interface=NAME".
Traceback (most recent call last):
  File "./krack-test-client.py", line 615, in <module>
    attack = KRAckAttackClient()
  File "./krack-test-client.py", line 349, in __init__
    self.apmac = scapy.arch.get_if_hwaddr(interface)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 51, in get_if_hwaddr
    addrfamily, mac = get_if_raw_hwaddr(iff)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 95, in get_if_raw_hwaddr
    return struct.unpack("16xh6s8x",get_if(iff,SIOCGIFHWADDR))
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 19, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16s16x", iff))
IOError: [Errno 19] No such device

This is the error that i am getting when i change the interface name in hostapd.conf. Can u suggest me a solution for this error??

**Comment by famoser** [comment]
The `IOError` says `No such device`, so does `wlan0` exist on your device? Run `ip link show` and verify `wlan0` is in the resulting list.

**Comment by vighnesh91** [comment]
I checked it does show that wlan0 exists.

**Comment by vanhoefm** [comment]
Please report issues to the github repository of the scripts: https://github.com/vanhoefm/krackattacks-scripts
